### ISSUE TITLE
Add general SME qualities to website

### ISSUE THREAD

**Issue by sstrassberg** [usds/SME-QA-Website#146] opened 2020-02-07 16:00 UTC
Update SME qualities to include general characteristics to aid HR in selecting quality SMEs for Job Analysis, etc.

List found here: https://github.com/usds/SME-QA/blob/master/agency-engagements/SME%20Qualities%20Checklist.md

**Comment by humancompanion-usds** [comment] 2020-02-13 21:31
This is a duplicate of issue #137

**Closed by humancompanion-usds** 2020-02-13 21:31 UTC
Labels: Site, high
